name: app
type: php:7.1.1
build:
    flavor: composer
disk: 2048 #2G

web:
    locations:
        "/":
            root: "app"
            passthru: "/index.php"
            index:
                - index.php
            allow: true




# # .platform.app.yaml

# # The name of this application, which must be unique within a project.
# name: 'app'

# # The type key specifies the language and version for your application.
# type: 'php:7.0'

# # The size of the persistent disk of the application (in MB).
# disk: 2048

# # The configuration of the application when it is exposed to the web.
# web:
#     locations:
#         '/':
#             # The public directory of the application relative to its root.
#             root: 'web'
#             # The front-controller script which determines where to send
#             # non-static requests.
#             passthru: '/app.php'
#         # Allow uploaded files to be served, but do not run scripts.
#         # Missing files get mapped to the front controller above.
#         '/files':
#             root: 'web/files'
#             scripts: true
#             allow: true
#             passthru: '/app.php'