name: app
type: php:7.1
build:
    flavor: composer
disk: 2048 #2G

web:
    locations:
        "/":
            root: "public"
            passthru: "/index.php"
            index:
                - index.php
            allow: true