name: app
type: php:5.5
build:
    flavor: composer
disk: 2048 #2G

web:
    locations:
        "/":
            root: "src/templates"
            passthru: "/index.php"
            index:
                - index.php
            allow: true

mydatabase:
    type: mysql:10.0
    disk: 1024

relationships:
    database: "mydatabase:mysql"