name: app
type: php:5.5
build:
    flavor: composer
disk: 2048 #2G

web:
    locations:
        "/":
            root: "public"
            passthru: "/index.php"
            index:
                - index.php
            allow: true

relationships:
    database: 'database1:mysql'