name: app
type: php:5.6
build:
    flavor: composer
disk: 2048 #2G

web:
    locations:
        "/":
            root: "src/templates"
            passthru: "/index.php"
            index:
                - index.php
            allow: true
    commands: 
        start: php run.php
    upstream:
        socket_family: tcp
        protocol: http

relationships:
    database1: 'php_poo:mysql'