# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: nomdelabasededonnees
      POSTGRES_USER: marc
      POSTGRES_PASSWORD: saucisson
    volumes:
      - cours:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  cours: